name: VerificationPlugin
version: '${version}'
main: de.hage.verification.VerificationPlugin
api-version: '1.21'
depend:
  - Vault
softdepend:
  - LuckPerms

commands:
  verification:
    description: Verifiziert Spieler und zeigt Verifizierungsinformationen
    usage: /verification <new|info|history|ui|resetmessages> [Spieler]
    aliases: [verify]

permissions:
  verification.new:
    description: Darf Spieler verifizieren
    default: op
  verification.info:
    description: Darf Verifizierungsinformationen anzeigen
    default: op
  verification.history:
    description: Darf die Verifizierungs-Historie anzeigen
    default: op
  verification.ui:
    description: Darf das Verifizierungs-UI öffnen
    default: op
  verification.ui.all:
    description: Darf im UI alle verifizierten Spieler sehen
    default: op
  verification.resetmessages:
    description: Darf die messages.yml mit der JAR-Version überschreiben
    default: op