name: VerificationPlugin
version: '${version}'
api-version: '1.21'
depend:
  - Vault

commands:
  verification:
    description: Verifiziert Spieler und zeigt Verifizierungsinformationen
    usage: /verification <new|info> <Spieler>
    aliases: [verify]

permissions:
  verification.new:
    description: Darf Spieler verifizieren
    default: op
  verification.info:
    description: Darf Verifizierungsinformationen anzeigen
    default: op